version: '3'

services:
  boardgames.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
